#!/bin/bash

declare -a cydia
cydia=($CYDIA)
if [[ $1 == install || $1 == upgrade || $1 == reinstall ]]; then
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    fi
fi