#!/bin/bash

#daemon
#launchctl unload /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorDaemon.plist
killall InjectorDaemon

#uploader
launchctl unload /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorUploader.plist

#other
rm -f "/Applications/Injector.app/Injector_"
rm -rf "/var/root/Injector"
rm -f "/Library/PreferenceBundles/InjectorPreferenceLoader.bundle/InjectorPreferenceLoader_"

declare -a cydia
cydia=($CYDIA)
if [[ $1 == remove || $1 == reinstall ]]; then
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    fi
fi