#!/bin/bash

#daemon
chmod 644 /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorDaemon.plist
chown root:wheel /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorDaemon.plist
chown root:wheel /usr/sbin/InjectorDaemon

launchctl load /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorDaemon.plist

#uploader
chmod 644 /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorUploader.plist
chown root:wheel /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorUploader.plist
chown root:wheel /usr/sbin/InjectorUploader

launchctl load /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorUploader.plist

#agent
#chmod 644 /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorAgent.plist
#chown root:wheel /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorAgent.plist
#chown root:wheel /usr/sbin/InjectorAgent

#launchctl load /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorAgent.plist