#!/bin/bash

#daemon
#launchctl unload /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorDaemon.plist

#agent
#launchctl unload /Library/LaunchDaemons/tw.edu.mcu.cce.nrl.InjectorAgent.plist

#other
#rm -rf /var/root/Documents/packetflowtemp/
#rm -f /var/root/Documents/InjectorUpdateLog
#rm -f /var/root/Documents/maliceDatabase

declare -a cydia
cydia=($CYDIA)
if [[ $1 == remove || $1 == reinstall ]]; then
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    fi
fi